### Kuroshio Extension, North Pacific Atmosphere, Northeast Marine Heatwaves

As my doctoral dissertation research I, have been working on how Kuroshio Extension in the North Pacific Ocean influences the atmosphere of the North Pacific by influencing Pacific Decadal Precession - a quasi decadal variability of a pressure dipole over the North Pacific. This work was further extended to determine how Kuroshio influences marine heatwaves in the northeast Pacific. Currently, I am investigating the future of these links in a changing climate.

### Gulf Stream Warm Core Rings - Shifts, Variability, and Survival

Investigated the long-term variability of Gulf Stream\'s Warm Core Rings. Developed a Survival model to investigate the survival of the Gulf Stream\'s Warm Core Rings. Conducted analysis on long-term regime shifts in Gulf Stream\'s Warm Core Ring formations. Conducted a georeferenced census for Gulf Stream\'s Warm Core Rings.

### Dugong and Seagrass Conservation in the Gulf of Mannar

Affiliated with Dugong and Seagrass Conservation cross-national project.

Developed and supplied inputs for the determination of a new marine protected area (MPA) in the Gulf of Mannar, Indian Ocean.

Conducted a survey to test the attitude of fishing communities for the conservation of Dugong and Seagrass in Gulf of Mannar and Palk Bay, Indian Ocean.

### Multi Purpose Water Infrasturcture Management in Central Asia

Developed a repository of muti-purpose water infrastructure case studies to utilize as an input for a policy model established for the management of reservoirs in Kazakhstan.

### Water Resources Management in South Asia and Africa

Analyzed hydrological data for ten different climate change scenarios produced as a SWAT model output to understand the hydrological impacts of climate change in the Tana River basin, Kenya.

Studied the potential of utilizing groundwater and surface water conjunctively for irrigation in an agricultural development scheme in North-Central Sri Lanka.

Processed a geo-coded agro-well database to calculate potential cropping intensities for an agricultural development scheme in North-Central Sri Lanka.

Contributed to a case study on small-scale hydropower generation and its implications on mountain streams in Sri Lanka
